title: Tutorial 2 Ghithub
author: anuar-fp
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Esto es un tutorial para guithub.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
